### PR TITLE
Weighting of LAN members and additions to WestLAN

### PR DESCRIPTION
**Pull request by CWFranklin**

### CODE REVIEW

**Review by mintopia — APPROVED** [review]

**Comment by VibroAxe** [comment]
Happy to merge, do you want to add website and event info for westlan first?

**Comment by CWFranklin** [comment]
We have website and a small amount of event info already present :)

**Comment by VibroAxe** [comment]
I'd suggest adding website and location as a minimum
```
 ## Website
 [epiclan.co.uk](https://www.epiclan.co.uk)
 ## Location
Stoke-on-Trent, Staffordshire
```

**Comment by VibroAxe** [comment]
Whelp, i totally missed the concatenator :S 

Merging

**Review by VibroAxe — APPROVED** [review]

**Pull request merged**
